create type public.user_role as enum ('member', 'journalist', 'admin');
create type public.comment_status as enum ('pending', 'approved', 'rejected');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  avatar_url text,
  bio text,
  role public.user_role not null default 'member',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table public.articles (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories(id) on delete set null,
  author_id uuid references public.profiles(id) on delete set null,
  title text not null,
  slug text not null unique,
  excerpt text not null,
  content text not null,
  thumbnail_url text,
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  is_trending boolean not null default false,
  is_featured boolean not null default false,
  views_count integer not null default 0,
  likes_count integer not null default 0,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.comments (
  id bigint generated by default as identity primary key,
  article_id bigint not null references public.articles(id) on delete cascade,
  member_id uuid references public.profiles(id) on delete set null,
  body text not null,
  status public.comment_status not null default 'pending',
  created_at timestamptz not null default now()
);

create table public.article_likes (
  article_id bigint references public.articles(id) on delete cascade,
  member_id uuid references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (article_id, member_id)
);

create table public.article_favorites (
  article_id bigint references public.articles(id) on delete cascade,
  member_id uuid references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (article_id, member_id)
);

create table public.banners (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text,
  target_url text,
  placement text not null,
  is_active boolean not null default true
);

create table public.ads (
  id bigint generated by default as identity primary key,
  brand text not null,
  slot text not null,
  image_url text,
  target_url text,
  status text not null default 'active'
);

create table public.site_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.articles enable row level security;
alter table public.comments enable row level security;
alter table public.article_likes enable row level security;
alter table public.article_favorites enable row level security;
alter table public.banners enable row level security;
alter table public.ads enable row level security;
alter table public.site_settings enable row level security;
alter table public.contact_messages enable row level security;

create policy "Public can read published articles" on public.articles
  for select using (status = 'published');

create policy "Public can read categories" on public.categories
  for select using (true);

create policy "Public can read active banners" on public.banners
  for select using (is_active = true);

create policy "Members manage own profile" on public.profiles
  for all using (auth.uid() = id) with check (auth.uid() = id);

create policy "Members create comments" on public.comments
  for insert with check (auth.uid() = member_id);

create policy "Members read approved comments" on public.comments
  for select using (status = 'approved' or auth.uid() = member_id);

create policy "Members manage own likes" on public.article_likes
  for all using (auth.uid() = member_id) with check (auth.uid() = member_id);

create policy "Members manage own favorites" on public.article_favorites
  for all using (auth.uid() = member_id) with check (auth.uid() = member_id);

create policy "Journalists manage own articles" on public.articles
  for all using (auth.uid() = author_id) with check (auth.uid() = author_id);

create policy "Admin full access profiles" on public.profiles
  for all using ((select role from public.profiles where id = auth.uid()) = 'admin');

create policy "Admin full access articles" on public.articles
  for all using ((select role from public.profiles where id = auth.uid()) = 'admin');

create policy "Admin full access comments" on public.comments
  for all using ((select role from public.profiles where id = auth.uid()) = 'admin');

insert into public.categories (name, slug, description) values
  ('Nasional', 'nasional', 'Berita nasional terkini'),
  ('Politik', 'politik', 'Kebijakan dan dinamika politik'),
  ('Ekonomi', 'ekonomi', 'Bisnis, pasar, dan finansial'),
  ('Teknologi', 'teknologi', 'Inovasi dan transformasi digital'),
  ('Olahraga', 'olahraga', 'Kompetisi dan prestasi olahraga'),
  ('Lifestyle', 'lifestyle', 'Gaya hidup dan budaya');
